var SGLang = {
	PublicMsg				:	"系统提示",
	MapUnit					:	"坐　标",
	MapUser					:	"君　主",
	MapVillage				:	"城镇名",
	MapPopu					:	"居　民",
	MapAlliance				:	"联　盟",
	ReportSendMsg			:	"发信",
	ReportFrom				:	"来自",
	ReportOasis				:	"绿洲",
	ReportSoldier			:	"兵种",
	ReportSoldierNum		:	"军队数量",
	ReportLoss				:	"损失",
	ChatAll					:	"综合",
	ChatWorld				:	"世界",
	ChatAlliance			:	"联盟",
	ChatSystem				:	"系统",
	ChatPersonal			:	"私聊",
	ChatAllUser				:	"群聊",
	ChatMsgConSucc			:	"聊天室连接成功。",
	ChatMsgConClose			:	"与聊天室断开连接。",
	ChatTagNull				:	"无",
	ChatMsgServerErr		:	"连接服务器错误",
	ChatMsgParErr			:	"请求参数错误，请稍后重试。",
	ChatMsgLoginCheckErr	:	"登录认证错误。",
	ChatMsgHadLoginErr		:	"您在另一个地方已登录，请您重试。",
	ChatMsgNoLoginErr		:	"您还没有登录。",
	ChatMsgActUnallow		:	"本次操作被限制，请稍后重试。",
	ChatMsgUnfind			:	"找不到指定的频道。",
	ChatMsgPlayerOutline	:	"该玩家不存在或已下线。",
	ChatMsgLenOver			:	"您的发言超出长度限制。",

	PageFirst				:	"首页",
	PagePrevious			:	"上页",
	PageNext				:	"下页",
	PageLast				:	"尾页",

	ValidateCodeDark		:	"看不清,请点击图片",
	ConsumeByCoin			:	"金币消费",
	ConsumeByTicket			:	"礼金券消费",
	ConsumeByRune			:	"铸币消费",
	ConsumeCoin				:	"金币",
	ConsumeTicket			:	"礼金券",

	VillageFullUnit			:	"请输入城镇完整座标",
	VillageUnitInt			:	"座标必须是数字",
	SelectSinkUser			:	"请选择指令接收人",

	AvgResourceFirst		:	"第一步：分配资源",
	AvgResourceNext			:	"下一步",
	AvgResourceSecond		:	"第二步：确认分配",
	AvgResourcePrevious		:	"上一步",
	AvgResourceConfirm		:	"本次操作需要扣除您<strong class=\\\'red\\\'>[XXX]</strong>个金币，请问您要继续么？",
	AvgResourceOK			:	"确定",
	AvgResourceCur			:	"当前资源：",
	AvgResourceAfter		:	"交易后资源：",
	AvgResourceChange		:	"资源变化：",
	AvgResourceAll			:	"所有资源：",
	AvgResourceDistribute	:	"分配资源：",
	AvgResourceRemanent		:	"剩余资源：",

	WarvacUnallowAttact		:	"休假模式不允许攻击别人",
	WarvacUnallowToAttact	:	"适逢盛节，此地止战，该城无法被攻击！",
	WarInputVillageName		:	"请输入城镇名称",
	WarSelectTarget			:	"请选择出兵目标",
	WarSelectSoldierClass	:	"请选择出兵类别",
	WarSelectSoldierType	:	"请选择出兵兵种",
	WarSelectScoutType		:	"您只选择的侦查兵种，请使用侦查模式！",
	WarvacCannotdestroy		:	"此城止战，无法破坏城镇建设！",

	HoleSelectSoldierType	:	"请选择兵种",
	GeneralLevelLimit		:	"武将达到1级以后才能带兵出征！",
	SoldierRaiseNum			:	"请输入需要招募的士兵数量",
	SoldierInjuredNum		:	"请输入需要疗伤的士兵数量",
	SoldierRaiseAutomove	:	"开启了<strong class='green'>明修暗渡</strong>，招募后会前往其他城镇。",
	WalldefenceBuildNum		:	"请输入需要建造[XXX]的数量",
	SoldierTypeNoExist		:	"招募兵种不存在",
	SoldierShortResource	:	"您的资源不足，无法招募到[XXX]",
	SoldierPCRaise			:	"招募助手可以招募到[XXX]个[ZZZ]，将花费您[YYY]个金币。",
	SoldierOpenAutomove		:	"（[XXX]开启了明修暗渡，招募后会前往其他城镇。）",
	TowerSoldierNumError	:	"释放的士兵数量超过箭塔内该类士兵的总数！",
	LocalSoldierNumError	:	"进入的士兵数量超过城内该类士兵的总数！",
	LocalSoldierUpLimit		:	"进入的士兵数量超过箭塔上限！",
	TowerSoldierResetError	:	"调整数量错误",
	TowerSoldierUpLimit		:	"箭塔中的士兵数量已达上限！",

	GeneralSelectTask		:	"请选择执行任务的武将",
	GeneralConfirmDemob		:	"您确定要放逐选定的武将么？",
	GeneralRentDays			:	"重金犒赏史实武将 [AAA] [BBB] 金币，[AAA]的效命期增加[CCC]天",
	GeneralAppointConfirm	:	"任命太守需要每种资源 <strong class=\"red\">[XXX]</strong> 单位，您确定要继续么？",
	GeneralDisappointConfirm:	"您确定要撤销选定的武将的太守职务么？",
	GeneralRevivalConfirm	:	"召回选定的武将需要 <strong class=\"red\">[AAA]</strong> 单位木材、<strong class=\"red\">[BBB]</strong> 单位石料、<strong class=\"red\">[CCC]</strong> 单位铁砂、<strong class=\"red\">[DDD]</strong> 单位粮食，您确定要继续么？",
	GeneralNameLenLimit		:	"武将名字的长度必须在4-10个字符之内！",

	ConsumeCoinConfirm		:	"本操作需要扣除您 <strong class=\"red\">[XXX]</strong> 个金币，您确定要继续么？",
	FloatInfoDisable		:	"<span style=\"color:#993366\">尚未激活</span>，点击购买。",
	FloatInfoEndTime		:	"结束于",

	TradeResourceLimit		:	"交易的资源值必须大于0",
	TradeResourceConfirm	:	"您确定用[XXX]买入[YYY]资源吗？",
	TradeResourceUnallowFull:	"资源数量不能全部都为空",
	TradeTargetVillageUnit	:	"请输入要运输的目标城市名或座标",
	TradeTargetConfirm		:	"确定将资源运输到[XXX]吗？",
	TradeSelfVillage		:	"请选择您的城镇",
	TradeSelfVillagename	:	"请填写城镇名称或坐标",

	SkillItemNoBook			:	"选中的技能栏没有技能书",
	SkillItemForgetSkill	:	"您确认将[AAA]技能书[BBB]中的技能（[BBB]级[CCC]级）遗忘吗？",
	SkillItemSeleceOne		:	"请选择一个技能栏",
	SkillItemNoOpenOne		:	"当前没有开启的技能栏",
	SkillItemNoFreeItem		:	"没有空余的技能栏，请先遗忘一本技能书",
	SkillItemByBook			:	"将技能书 [XXX] 学习到以下技能栏",
	SkillItemNum			:	"技能栏",

	GoodsContributeNumError	:	"数量输入错误",
	GoodsContributeConfirm	:	"确定献纳[AAA]个[BBB]（提高[CCC]点贡献度）吗",
	GeneralRenameInput		:	"请输入武将名称：（4-10个字符）",

	GoodsBuyNumError		:	"请输入您想购买的商品数量（大于0）",
	GoodsBestowName			:	"请输入赠送用户的君主名",
	GoodsBestowUserConfirm	:	"并将其赠与 <font color=\"green\">[XXX]</font>",
	GoodsIdError			:	"错误的道具ID",
	GoodsinputBestowNum		:	"请输入您想赠送的道具数量（大于0）",
	GoodsBestowNum			:	"您要将 <font color=\"blue\">[AAA]</font> <font color=\"red\">×[BBB] 赠与<font color=\"green\">[CCC]</font> 吗？",

	GeneralneedInfo			:	"缺少武将信息",
	GeneralMenumijiNo		:	"当前没有开启的秘籍栏",
	GeneralMenuallFull		:	"没有空余的秘籍栏，请先遗忘一本秘籍",
	GeneralMenumiji			:	"秘籍栏",
	GeneralStudyMiji		:	"将秘籍[XXX]学习到以下秘籍栏",
	GeneralInfoError		:  	"武将信息错误",
	GeneralNeedLevel		:	"装备需要武将等级达到[XXX]",
	TicketZero				:	"0礼金券",
	CoinsZero				:	"0金币",
	NewerTask				:	"新手任务",

	OtherVillage			:	"分城",
	MainVillage				:	"主城",
	JunVillage				:   "郡城",
	ZhouVillage				:	"州城",
	DiduVillage				:	"帝都",
	OldJunVillage			:   "旧郡",
	OldZhouVillage			:	"旧州",
	OldDiduVillage			:	"旧帝",
	Assistant				:	"陪都",

	ItemHaveno				:	"您没有该道具或该道具已使用",
	PageError				  :	"系统错误!请关闭该页面后再次使用",
	GetPrizeIng				:	"正在阅读,请稍等...",

	TaskTitle				      :	"任务：",

	ResourceFull				      :	"请尽快升级您的仓库和粮仓。",
	ResourceOverflow				      :	"本城资源已无法存储，请立即升级仓库和粮仓。",
	MapMountainvillage				      :	"土匪营寨",
	MapType				      :	"类　型",
	Newer1				     :'　　英雄请留步，民女见英雄气宇非凡，定是平定天下之明主，拯救乱世之枭雄。想您初来乍到，或许对这个世界还有些陌生，请允许民女把三国风云的基本操作做下介绍，将对您争霸天下大有帮助。',
	Newer2				     :'　　无论您是有精力对游戏进行经营的争霸玩家，还是休闲玩家，游戏同样适合您。您选择何种玩法，资源建设都是必不可少的。<br />　　资源产量在界面的黄色框中。请点击该框以示你已了解该内容。',
	Newer3				     :'　　提升资源田的等级，资源产量会相应提高。<br/>　　请点击界面上方“<b>资源</b>”标签。',
	Newer4				     :'　　<b>请选择一处粮田<b/>',
	Newer5				     :'　　请点击“<b>升级<b/>”',
	Newer6				     :'　　城市中正在升级的建筑将显示在这里，当倒计时结束后，建筑完成。<br/>　　（魏国可同时建造城内城外2个建筑，其他国家只能同时建造一个。）',
	Newer7				     :'　　除了粮田，还有木材，石料，铁矿，这些都属于资源类建筑。无论是修建建筑或招募士兵，都需要这些资源。另外士兵会不断地消耗粮食。在后期，粮食是影响士兵数量的最大因数之一。',
	Newer8				     :'　　除了资源建筑，还有基础建筑和军事建筑，可以在<b>城郭</b>中选择建造。',
	Newer9				     :'　　乱世之中，孤掌难鸣，加入距离你较近且实力强大的联盟，以达到群狼战虎的目的是你最好的选择。<br/>　　请在上方点击<b>联盟</b>',
	Newer10				     :'　　乱世之中，孤掌难鸣，加入距离你较近且实力强大的联盟，以达到群狼战虎的目的是你最好的选择。<br/>　　请在上方点击<b>联盟</b>',
	Newer11				     :'　　任务界面将是你在游戏前期中最常用的一个界面之一。完成任务可以获得各种丰厚的奖励。<br/>　　请在上方点击<b>任务</b>',
	Newer12				     :'　　工欲善其事，必先利其器。为您的武将装备上精良的装备，或是凭一小小锦囊上演点石成金的传奇，在商城处购买道具，这些道具将助您轻松争霸天下。<br/>　　请在上方点击<b>商城</b>',
	Newer13				     :'　　无论是购买或者通过其他途径获得的道具，我们都帮您储存在您的私人宝库中。<br/>　　请点击<b>宝库</b>.',
	Newer14				     :'　　如果您的金币不足，我们为您提供了最快速，最方便，多种途径的充值方式。<br/>　　请点击<b>充值</b>',
	Newer15				     :'　　如果你在游戏中发现任何问题，请通过点击<b>客服</b>标签，联系我们的在线客服。<br/>如果您对游戏有疑问，或者想和其他玩家交流经验心得，也可进入<b>论坛</b>，寻找相关内容，发布您的游戏心情。',
	Newer16				     :'您好，欢迎您来到丰富多彩的《三国风云》游戏世界！<br>您正处于新手保护期期间，为期7天，请您利用这段时间高筑墙，广积粮，以备未来争霸天下',

	InputCoins				:	"请输入金币数量",
	Out7canBuy				:	"开服7天内无法进行资源购买",
	CoinsNoEnough			:	"您所持的金币不足",
	InputCorrectNum : "请输入正确的数量",
	UseCoins				:	"花费<strong class='red'>[AAA]</strong>金币购买资源[BBB]",
	InputError				:	"输入的金币数量错误",

	CountError				:	"输入数值不正确",
	AllianceBuy				:	"使用后联盟物资增加[XXX]点，您对联盟的贡献度也将增加[XXX]点<br>您确定要捐献这些物资吗？",

	ErrorSelectGeneral		:   "请选择武将",
	ImproveExpFreeLeft		:	"今日剩余[AAA]人次免费修炼机会，可节省[BBB]金币。",
	ImproveExpFreeTips		:	"使用免费修炼机会",
	TaskNew					:   "新任务",
	TaskFinished			:	"完成",
	TaskUnfinished			:	"未完成",
	///V2.3.1新增
	ChatNoFindPersonal		:	"私聊频道没有私聊对象",
	UndressScrollCnt		:	"卸下数量：",
	dressScrollCnt			:	"装备数量：",
	Guidenewer	:	"新手指南",
	Guidepro	:	"常见问题",
	Guideintro	:	"游戏介绍",
	Guiderule	:	"游戏规则",

	///V2.3.2新增
	ErrorSkillbookUpgrade1	:	"请选择要升级的技能书",
	ErrorSkillbookUpgrade2	:	"缺少祭书",
	ErrorSkillbookCompose1	:	"缺少技能书",
	sellConfirm				:	"你确认要出售吗？",
	quickUse				:	"使用",
	ErrorUpgradeItemFull	:	"祭书栏已满",
	ErrorComposeItemFull	:	"合成栏已满",
	ErrorItemNotEnough		:	"道具数量不够",
	//V2.4新加
	ItemGoods285		:	"召回令 现有：",

	//2.3.0追加
	SinanPlaying 		:	"正在抽取奖品，请稍候...",
	SinanContinueTips	:	"[NUM]秒后自动开启下一个。",
	PubStop				:	"停止",
	PubContinue			:	"继续",

	//v2.4.1
	SmeltDecomposeNum: "分解数量: ",
	NowHave: "现有: ",
	ErrorNoInputItemNum : "请输入道具数量",
	ConfireDecompose : "确认分解以下装备吗？",
	SmeltDecomposeMulti : "批量分解",

	//v2.6.0
	ResearchQuestionUnfinish: "问卷未完全填写",

	Forget_UseSkill:"确认将技能书YYY遗忘吗？",
	Forget_Use_Buy_TT:'您当前偷天换日数量不足，<a onclick="MM_xmlLoad(\'store.main&category=1&haverebate=1\');return false;" style=\'color: rgb(51,153,102); font-weight: bold;text-decoration:underline; cursor:pointer;\'>请点击这里购买</a>',
		//v 2.7.0
	NormalDemolish:"普通拆除",
	QuiteDemolish:"彻底拆除",
	DZwar_ask:"此服务器为玩家强制对战服务器，如果您确认可以以此模式游戏，请点击确认继续。",
			//wcd facebook
	SendGift12	:		'赠送礼物',
	GetGift34		:		'接收礼物',
	TKDGiftSend  :		'三国风云礼物赠送',
	TKDom        :		'三国风云',
	ComeOnGo :			'快来一起在三国风起云涌吧',
	ReceiveAsk :			'接受邀请',
	TKDGameInvite :	'三国风云游戏邀请',
	//v 2.8.0
	UcopyCanNotMove	:	'移动冷却期间武将不能行动！',
	//v3.0.1细节修改
	ResBagUseCntErr :	'请输入正确的资源袋使用数量！',
	ResBagDailyOver :	'今天的资源袋可用次数已经用完，不能再使用了！',
	IllegalCharacter:   '输入非法字符！',
	
	RandGiftUseCntErr: '请输入正确的使用数量！',
	
	NpcRandGiftUseCntErr: '对不起你选择的操作类型有误，请重新选择！',
	ConsumeZhubi: '铸币',
	ChangeNoErr: '对不起，兑换数量不能为0！',
	NeedCoin: '需要金币：',
	NeedTickte: '需要礼金券：',
	NeedRune: '需要铸币：'
};